### ISSUE TITLE
Practice Incremental Exam Submission Error

### ISSUE THREAD

**Issue by Ailikekaus** [Section508Coordinators/DHSA-TT-200-A#115]
## Issue Type (put an X between the brackets to indicate issue type)
- [x] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Application not saving user submitted results correctly.
Chrome browser "Version 74.0.3729.131 (Official Build) (64-bit)"

## Location
Incremental Practical Exam for Topic 2: Auto-Playing and Auto-Updating Content 

## Actual Behavior / Observation
The exam portion of Trusted Tester training software is extraordinarily disappointing.  

I took the Incremental Practical Exam for Topic 2: Auto-Playing and Auto-Updating Content and encountered numerous problems. 

The software failed my first attempt, stating I did not pass the 2.2.2-blinking-moving-scrolling question.  Disappointing, but perhaps I missed something, after all the options available for answering each question are not necessarily in the format one desires.

I chose to fail the 2.2.2-blinking-moving-scrolling question, based on the fact there is no mechanism that can pause, stop, or hide the blinking text content: "Physical Health on-Hold".
![image](https://user-images.githubusercontent.com/19952958/59472943-374d2600-8e0e-11e9-9d12-07b8064633be.png)

Instead of an answer option of "there is mechanism that can pause, stop, or hide…", the answer page displayed: 
"Select all Elements that are Not Compliant with Test ID 2.B." with a number of checkboxes for content elements on the page.
The only close option the exam presented was the check box: "REGION 3 - Physical Health Large Text", which I selected.
![image](https://user-images.githubusercontent.com/19952958/59472963-43d17e80-8e0e-11e9-9c67-74cc823409a2.png)

I submitted my results (I sure wish I had taken a screen shot to prove my answers), and got results stating only 75% passing with my answer for 2.2.2-blinking-moving-scrolling failing.

I attempted the exam a 2nd time, not sure what could be the "correct" answer and thought that maybe the answer should be that the text "Physical Health on-Hold" was Flashing instead of Blinking.  I entered "DNA" for "Does Not Apply".  The results for this attempt were the same only 75% passing with my answer for 2.2.2-blinking-moving-scrolling failing.

Now, I was quite perplexed because the answer certainly can't be PASS because the text is obviously Blinking/Flashing (or something) and does not have a mechanism that can pause, stop, or hide it.

I took the test a 3rd time, reviewing the answers carefully, and being quite stubborn decided to select the check box: "REGION 3 - Physical Health Large Text" for a second time because that is exactly where the blinking text "Physical Health on-Hold" is (I should have taken a screen shot).

Imagine my surprise when the test results returned with 100% (I should have taken a screen shot so I can prove it).  

Great, at least I passed the first Incremental Practical Exam - or did I?  When I returned to the course overview page, it still showed that I have not passed the exam.

I'm not surprised. This software is definitely NOT ready for prime-time.  I had heard much about the software failings from EVERY Trusted Tester I have spoken with who took the online training in the past.  I thought OAST was past this and that we were getting new software.  This is very disheartening and disappointing to see.  Perhaps there is an issue with network latency, but this should not be the students' fault if the software is not up to the task.  

I do know what the standard answer will be because I've already heard it from all the other Trusted Testers - "there is no record of an error; this is the results we have…"  The problem is not with the results, rather it is a problem with the application not saving user submitted results correctly.  I know what I saw, I just wish I had taken screen shots to prove it.

## Expected Behavior / Recommendation
Expect the exam to save the options students submit.

## Steps to Reproduce the Issue (if applicable)
This is an issue that can’t be easily repeated, but seemingly randomly occurs.

**Comment by drewnielson** [comment]
1. Thanks for your feedback. There does appear to be some issue with the exam returning feedback when a user does not click the exit button after submitting results. We'll look into the issue further. While we have provide some instruction in the introduction to direct students to click the "Exit" link before closing the exam and to refresh the page in order to update the Incremental Exam completion status in the Course main page, that text could be easy to miss or forget. I have added text below each Incremental Exam activity to direct students to "Exit" before closing the exam window and to refresh the course page in order to update the exam activity completion status.
2. Please reach out to the Accessibility Helpdesk (accessibility@hq.dhs.gov) to schedule a 1 on 1 session with me. I have access to view the pages that were generated for each of your attempts as well as your responses. I would be happy to talk through what you missed and why you missed it.
3. Please recognize that there are actual living, breathing people on the other end here reading, reacting, and responding to your comments. Also please remember that you are part of a pilot, which means that you are essentially beta testing this course and the accompanying incremental exams. If you expect to complete the course without encountering any issues, then you might not be a good candidate for the pilot. If you do continue in the pilot, then I will expect a larger portion of courtesy from you. If you would rather wait until the course really is ready for prime time, you are welcome to do just that.

**Comment by Ailikekaus** [comment]
@drewnielson 

1.  Thought I followed the procedure correctly, but will be sure to take a much closer look the next time I take an incremental exam so that I will be prepared to document.  This also gives me a some good ideas for testing the exam.  Thanks.

2. I will contact the Accessibility Helpdesk (accessibility@hq.dhs.gov) to schedule a 1 on 1 session with you. I don't have time today, but will ask for time next week.

3.  Sorry if I offended (I had high expectations), but also recognize that people's employment depends on this exam.  I do know people who lost their jobs for not being able to pass.  I often wonder about those who pass who perhaps should not have.  All the Trusted Testers I know are quite concerned about this very issue.  
I didn't expect to complete the course without encountering errors, but also didn't realize this is the same software that had this known exam submission problem (as such, this can't still be beta).  It would have been beneficial to have been told that the exams themselves may still have problems.

**Comment by Tonylayton1** [comment]
There are 2 correct answers to this ID: the text is blinking and cannot be stopped, and the video auto-plays and cannot be paused (one or both of these may occur, but if both are present, listing both is required to be counted correct). Unfortunately this auto-play function is circumvented by certain browsers at the moment, which is a separate but known issue. This will cause a false-negative resulting in the frustrating issue that this tester has run into.

I believe both issues (video autoplay not working in certain browsers, answers not saving) are already known and being addressed.

**Comment by Tonylayton1** [comment]
Please verify that the second half of this issue is described sufficiently in issue #91 

as for the video autoplay, there wasn't an issue in here yet, so:

In Chrome and Firefox, autoplay is circumvented by the browser (this is a new feature in both browsers), which will cause users to report false-negatives on 2.A and 2.B if the expected answer is NC.

**Comment by drewnielson** [comment]
Closing issue. Autoplay issue will need to be described in a separate issue. Other issues addressed with last Friday's deployment to the incremental exams.
