### ISSUE TITLE
Incremental not listing incorrect IDs

### ISSUE THREAD

**Issue by cdizon5** [Section508Coordinators/DHSA-TT-200-A#129]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [X ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
If you answer a question incorrectly on an incremental, it is supposed to tell you which IDs you answered incorrectly.  There have been multiple instances where it will say "Below are the IDs that are incorrect" however it does not list any IDs.  It is just blank.  

## Location
No specific location as it occurs throughout multiple topics.

## Actual Behavior / Observation
There have been multiple instances where it will say "Below are the IDs that are incorrect" however it does not list any IDs.  It is just blank.  

## Expected Behavior / Recommendation
Expected behavior is the IDs would appear for the questions you got incorrect.

## Steps to Reproduce the Issue (if applicable)
Access an incremental for one topic (links for example). Answer one of the IDs incorrectly.  After submitting your answers, it should tell you which IDs you answered incorrectly.  Sometimes it will show you the IDs, however other times it will be blank (even though IDs should be listed).

[Missing IDs.docx](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3298194/Missing.IDs.docx)

**Comment by drewnielson** [comment]
Thanks @cdizon5. Could you do me a favor and experiment with a few attempts with submitting answers and then clicking the Exit button in the incremental before closing the browser window vs. submitting answers and NOT clicking the Exit button before closing the browser window? It appears that the issue happens when the user submits an attempt, DOESN"T click Exit, and then submits another attempt after that. However, if the user does click Exit after each attempt, then it doesn't seem like we see the issue. If this observation is correct, then we have a fix in the Dev environment that should resolve the issue. If not, then there must be something else going on. If you wouldn't mind helping us investigate with another set of eyes, I'd really appreciate it. Thanks!

**Comment by drewnielson** [comment]
This is also related to issue #115

**Comment by cdizon5** [comment]
I always hit the Exit button to leave the page.  It happens sporadically, so it's hard to pinpoint.  If I answer incorrectly and the IDs do not appear: I hit Exit, go back to course, refresh the page, enter the incremental, and then try again.  Sometimes the incorrect IDs will appear, but sometimes it's blank.

**Comment by drewnielson** [comment]
Ugh - OK, thanks. Next time it happens, can you grab a screenshot of the blank results page and also note the URL for that specific incremental?

**Comment by AnnMarieDavis** [comment]
This has happened to me as well - using the same process that Chris is using. However, even though I may not see what I missed, when I go back in to the exam, it does seem to be updating the options that are displayed when you try to retake.  Still, we do want to determine why this is happening and if I run into it again I will also try to document it.

**Comment by AnnMarieDavis** [comment]
This is documented in Issue [[#186](https://github.com/Section508Coordinators/DHSA-TT-200-A/issues/186)]

**Comment by drewnielson** [comment]
Fix was applied in last Friday's deployment to the incrementals. Closing the issue. If we note continued instances, will re-open this issue.
