### ISSUE TITLE
Printed books that open in Adobe Acrobat do not support search

### ISSUE THREAD

**Issue by jcarrschwab** [Section508Coordinators/DHSA-TT-200-A#134]
If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues.

## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ x] Other, specify...suggestion to improve materials

## Description
Because we can access course materials for a limited time, I'm printing each book as a go. I expected that opening the books in Adobe would allow me to search for key text when I needed to reference it. I am not getting this result. 

Recommendation:
Ensure better PDF support
Post each book as a PDF for download within the site without the user taking the extra step to "print book"

**Comment by drewnielson** [comment]
Thanks for raising the issue @jcarrschwab. Looks like we'll need to add some more specific instructions depending on browser. Looks like it might be an issue with the browser-specific plug-ins. What browser are you using? 

I see the same issue in Chrome; however, if I select "Save as PDF" instead of "Print to PDF" then the text is searchable. If you're using Chrome, give that a try and let me know if that at least gives you what you need for now.
![image](https://user-images.githubusercontent.com/29068131/59633662-02e1ae80-911b-11e9-8eeb-5bcbafe81870.png)

Also tried in Edge, and the print to PDF created the PDF with searchable text. Haven't tried IE or Firefox yet.

@AnnMarieDavis, would you mind taking this one to add more specific text in the Introduction to direct users to "Save as PDF" instead of "Print to PDF" for chrome users? Will also need to look into whether users might have the same issue and/or whether specific instruction is needed for Firefox and IE.

**Comment by drewnielson** [comment]
We might consider including a PDF of each book/topic in the course resources, but have avoided that so we don't have to create a new PDF each time we make an update to course content. As long as the functionality works and we can make sure we let users know about the browser-specific peculiarities, then I'd like to continue to avoid having to create a PDF version of each book/topic.

**Comment by jcarrschwab** [comment]
I think this could be environmental. I tested this on my corporate network, and it works. So I'm wondering if it's my ICE set-up. Boooo.

**Comment by jcarrschwab** [comment]
I believe in a couple of cases I used Print to PDF and in others I used the Chrome function.

**Comment by drewnielson** [comment]
Hmmm - OK. Need to do a little more poking around on this one. Thanks!

**Comment by drewnielson** [comment]
Added note in Introduction under General Navigation to prompt students to select the "Save as PDF" in the destination selection in Chrome. Didn't notice the same issue in other browsers.
