### ISSUE TITLE
Do we need to add a small disclaimer in Course Intro> Disclaimers to note small browser differences?

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#142]
After the Lesson 1 in Keyboard (Topic 4, Lesson 1, Passing examples) shenanigans with different browser experiences, should we put a small disclaimer on the Course Intro> Disclaimer page along the lines of "You may notice very small discrepancies within the course interactive samples (any other place too??) depending on the browser used."

**Comment by drewnielson** [comment]
Yes, let’s add something in the intro. I don’t think it needs to be anywhere else.

**Comment by AnnMarieDavis** [comment]
Text added (italicized only to show what was added) to the Course Introduction,, Test Process (Topics 1-20) section (https://training.section508testing.net/mod/book/edit.php?cmid=1221&id=2610): 
Examples provided to help you learn to assess content for the test process are sometimes interactive. You are encouraged to take advantage of interactive elements to help you understand the content. Note: _Note: Because of differences between browsers, you may see small variations in how your browser displays sample content from the interactive examples._
