### ISSUE TITLE
Add language to note how to fill out incremental exams: to course intro, langugae on each exam results page?

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#151]
To answer this question: For the incremental exams do you have to select every failure on the page or just one of the failures?

What we need to add to the training:
We need specific information to tell testers how/what to mark. Old school testers only had to select say 2/4 errors. New rules are that you need to select ALL the failed items on the page. Also need to add language telling students how to mark loss of focus.

**Comment by AnnMarieDavis** [comment]
In the Course Introduction, added text to the **Incremental Exams** section: You should mark **every instance** of non-conformance for the topic when you review the web page.

Changes are still needed to the Incremental Exam questions.  The correct text is not provided on any of the Practice Exams. 
Current text reads: Do NOT test COTS plug-ins. The test results of COTS plug-ins are not reported here. In the new window that opens after you select Test This Page, press F12 to open the Developer Tools toolbar in Internet Explorer (IE). In IE 9, set "Browser Mode: IE9" and "Document Mode: IE9 Standards" to disable Compatibility View.

Text should be: 
Do NOT test COTS plug-ins. The test results of COTS plug-ins are not reported here. 
In the new window that opens after you select Test This Page, select the ANDI tool (training course) version from your browser toolbar. Remember: you must mark **every instance** where a test condition fails. 
Before you close the Incremental Practical exam, click the "Exit" link in the top, right-hand portion of the page. After you pass the Incremental Exam, you must **refresh this page** in order to update the completion status of this activity.

In addition for the KEYBOARD and FOCUS Incremental Exam only add this sentence to the end of the second paragraph: If there is a failure for Visible Focus, you **mark the last interactive element that received focus** on the answer page.

**Comment by AnnMarieDavis** [comment]
In addition, the grey banner bar on each incremental exam needs to be changed from "Certification Exam" to "Incremental Practice Exam"

**Comment by KSmithO** [comment]
Carney should already know that change

Thanks,
Kristen Smith| Senior Accessibility Technician
Office of Accessible Systems & Technology (OAST)
Department of Homeland Security, HQ
Supported by New Editions Consulting, Inc
Phone: (202) 774-0382;  (202) 578-8845
Email: Kristen.Smith@associates.hq.dhs.gov<mailto:Kristen.Smith@associates.hq.dhs.gov>

DHS Accessibility Help Desk
Phone: 202-447-0440
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/>
 Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>

This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If  the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this in error, please reply immediately to the sender and delete this message.

**Comment by KSmithO** [comment]
I like the language for course intro, but I also think this language needs to go on the Incremental, Practice, and Exam Test ID results pages as an extra reminder. People will not remember what they read right out of the gate.

The other editorial stuff Carney should already know about…

Thanks,
Kristen Smith| Senior Accessibility Technician
Office of Accessible Systems & Technology (OAST)
Department of Homeland Security, HQ
Supported by New Editions Consulting, Inc
Phone: (202) 774-0382;  (202) 578-8845
Email: Kristen.Smith@associates.hq.dhs.gov<mailto:Kristen.Smith@associates.hq.dhs.gov>

DHS Accessibility Help Desk
Phone: 202-447-0440
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/>
 Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>

This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If  the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this in error, please reply immediately to the sender and delete this message.

**Comment by AnnMarieDavis** [comment]
Agreed – I can’t make changes to the exams or the language that appears in moodle when they select the exam…

Kind Regards,
Ann Marie

iPhone: 202-815-5428
Room 2020-07
annmarie.davis@associates.hq.dhs.gov<mailto:annmarie.davis@associates.hq.dhs.gov>

[cid:42523328-67EE-43C4-AC62-F470BA4429D1]
      [2018 Leading Disability Employer Seal]

**Comment by KSmithO** [comment]
Right-that’s a carney thing for now.

Thanks,
Kristen Smith| Senior Accessibility Technician
Office of Accessible Systems & Technology (OAST)
Department of Homeland Security, HQ
Supported by New Editions Consulting, Inc
Phone: (202) 774-0382;  (202) 578-8845
Email: Kristen.Smith@associates.hq.dhs.gov<mailto:Kristen.Smith@associates.hq.dhs.gov>

DHS Accessibility Help Desk
Phone: 202-447-0440
Website: accessibility.dhs.gov<http://accessibility.dhs.gov/>
 Email: accessibility@hq.dhs.gov<mailto:accessibility@hq.dhs.gov>

This communication, along with any attachments, is covered by federal and state law governing electronic communications and may contain sensitive and legally privileged information. If  the reader of this message is not the intended recipient, you are hereby notified that any dissemination, distribution, use or copying of this message is strictly prohibited.  If you have received this in error, please reply immediately to the sender and delete this message.
