### ISSUE TITLE
Button names on media player

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#220]
## Issue Type (put an X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [x] Other, specify...[media player button purpose is unclear to some students]

## Description
[Some students have been confused about the button labeled AD on the media player. It has also been hard for them to determine when the AD or CC button is activated. Clarification of button names is needed.]

## Location
[http://3.217.25.10/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?studentEmail=annmarie.davis@associates.hq.dhs.gov&SCOInstanceID=222&examId=3,  Topic 2, Incremental Exam]

## Expected Behavior / Recommendation
1. Rename "Rewind" button to "Skip back"
2. Rename "Forward" button to "Skip forward"
3. Rename "CC" button to "Closed Captions On" and toggle with "Closed Captions Off"
4. Rename "AD" button to "Audio Description On" and toggle with "Audio Description Off"
5. Rename the button names on the answer sheet to Closed Captions and Audio Description

![Button names 2019-07-09](https://user-images.githubusercontent.com/31414225/60884492-fd0f5280-a21a-11e9-8eaa-930703ad19a5.png)

NOTE: This change may also need to be made on other answer sheets and pages with video players on the incremental exams.

**Comment by mikebarklage** [comment]
Not quite ready for QA yet, but FYI, instead of On or Off, I'm adding a check mark next to Closed Captions or Audio Description to signify they're on.

I'm also keeping the underlining because that's how the JS code knows whether to have those functions active or not in the video. (The underlining itself isn't necessary, it's whether the CSS class has been applied or not, but I don't see anything wrong with keeping it displayed.)

**Comment by AnnMarieDavis** [comment]
Mike,
A check mark alone will not meet the requirement since all screen readers may not be able to read the symbol.  You should also add an ARIA described by label.

Kind Regards,
Ann Marie

iPhone: 202-815-5428
Room 2020-07
annmarie.davis@associates.hq.dhs.gov<mailto:annmarie.davis@associates.hq.dhs.gov>

[cid:42523328-67EE-43C4-AC62-F470BA4429D1]
      [2018 Leading Disability Employer Seal]

**Comment by drewnielson** [comment]
Alternatively, an aria-label=“Closed Captions On” and aria-label=“Audio
Description On” for those buttons when the check mark is displayed would
override the inner text of the button so a screen reader would get the
benefit of the aria-label instead of the text with the check mark. While
we’re at it, might also want to add aria-labels to indicate off when the
check marks are not present on the buttons.

**Comment by mikebarklage** [comment]
OK, then I have to doublecheck: does "Closed Captions On" mean "the closed captions are currently on" or "click this button to turn on closed captions?"

If it's the former, I might go with "Closed Captions: On" with a colon.

**Comment by drewnielson** [comment]
Yes, good point. I would go with the former, so I like adding the colon:
“Closed Caption: On/Off”

**Comment by mikebarklage** [comment]
OK, these changes should be done.

I also updated the Rewind/Forward buttons on page 3 and the Rewind/Forward exam checkboxes for both pages.

I added aria-labels to the CC/AD buttons that change when clicked. ANDI doesn't pick up on the changes right away, though - if I click away and then back to the list of buttons, I see the new aria-label text.

**Comment by drewnielson** [comment]
Right, ANDI doesn’t play well with dynamic content yet. For each change in
content on the page, you have to click the refresh ANDI button in the ANDI
pane. We have given instructions to the students to that effect though, so
they should be aware they need to refresh ANDI to get info for
updated/changed content.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
verified in dev
