### ISSUE TITLE
Provide specific reasons for wrong answers in results

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/DHSA-TT-200-A#291]
A couple students have requested more specific feedback in order to better understand why they are getting questions wrong. Two possible solutions, at least for the incremental exams:
* On the results screen/email, indicate correct response and which elements should have failed.
* Provide the link to their test page for that attempt so they can review page to identify the correct answers now that they now what the answers should be.

@AnnMarieDavis, before we definitely make this happen, please weigh in and let's discuss with the rest of the gang.

@mikebarklage, in the meantime, can you think about how hard/how much time it would take to implement?

**Comment by drewnielson** [comment]
On further thought, let's investigate feasibility to provide a hint for a wrong answer and provide the ability to re-try the previous attempt.

**Comment by sonicbobcat85** [comment]
I would like to request that this be revisited. As a student taking this course with no instructor and no Q&A sessions available anymore, I'm heavily reliant on the incremental tests to ensure that I fully understand both the concepts and the input that this test format expects. Between the lack of verbose results and the inability to retake the tests in the same form (since they keep regenerating with each attempt), it's difficult to learn anything from them.

Verbose results on the practice test would be similarly useful, but that's a slightly different topic.

**Comment by drewnielson** [comment]
We’re definitely working on it. Can’t promise exactly when it will be ready
for release, but it is in process.

**Comment by Mark0068** [comment]
This is exactly what I was thinking!  If the purpose is to learn from one’s mistakes, this course misses the mark.

Another alternative is to identify the wrong answers, or eliminate the correct answers from further iterations.

Respectfully,


Mark Malamud
Westat | Section 508 Specialist
Accessibility Information Bureau (AIB)<https://wesinfo.westat.com/pages/research/accessibility/index.aspx>
RA 1231
301 294 2806
MarkMalamud@westat.com

Westat<https://www.westat.com/> | Facebook<https://www.facebook.com/westat.hq> | Twitter<https://twitter.com/westat> | LinkedIn<https://www.linkedin.com/company/westat>

**Comment by Tonylayton1** [comment]
This has been implemented in the incremental exams.

**Comment by AnnMarieDavis** [comment]
I'd love to hear some feedback from students about how they like this new feature.  It was one of our most requested enhancements and there has been silence since it was implemented.
