### ISSUE TITLE
WORKBALANCE text in background image should not be a failure for 7.A

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/DHSA-TT-200-A#301]
On the page below, when WORKBALANCE logotype is presented as a background image, it should NOT be included as a failure for 7.A. Test ID 7.A only applies to inline images.

https://exams-dev1-c.section508testing.net/dhsv5/scormapi/admin.php?SCOInstanceID=516&KeyID=2787&ExamID=7
https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?KeyID=2787

**Comment by Tonylayton1** [comment]
When 7.C fails, it shouldn't fail 7.A, so these two IDs can be unlinked. 

When the logo is a background image, 7.A should no longer be affected, and 7.C is "nc" just as it is now. 

note that there is a separate 7.A failure for the site logo image just above this. it should still fail as before, only difference is it is no longer tied to 7.C.

When 7.A fails, the reason should be r1_1 (no longer r1_1 and r1_2)
When 7.C fails, the reason is r1_2

**Comment by mikebarklage** [comment]
Updated.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by drewnielson** [comment]
In [this page example](http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?KeyID=1891), the WORKBALANCE logo text is a background image, but the [answer sheet](http://52.23.182.152/dhsv5/scormapi/admin.php?SCOInstanceID=170&KeyID=1891&ExamID=7) grades it as a pass.

But in [this page example](http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?KeyID=1894), the WORKBALANCE logo text is also a background image, but the [answer sheet](http://52.23.182.152/dhsv5/scormapi/admin.php?SCOInstanceID=170&KeyID=1894&ExamID=7) grades it as a fail.

**Comment by Tonylayton1** [comment]
it doesn't look like the webpage and the answer sheet are matching up for 7.C. could 7.C still be linked to 7.A in the webpage?

**Comment by mikebarklage** [comment]
7.A was still being used in both locations. I changed the word-logo to check 7.C instead.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
OAST verified 2 randomized pages
