### ISSUE TITLE
14.B error on answer sheet for Practice Exam

### ISSUE THREAD

**Issue by AnnMarieDavis** [Section508Coordinators/DHSA-TT-200-A#315]
## Issue Type 
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
The answer sheet states the Comparing Security table is NC, but it is located in a frame and IS properly coded.  The answer sheet should mark this a PASS (C)

## Location
Page 3: https://exams-dev1-c.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page3_frame2.php?KeyID=4174

https://exams-dev1-c.section508testing.net/dhsv5/scormapi/admin.php?SCOInstanceID=844&KeyID=4174&ExamID=2

**Comment by Tonylayton1** [comment]
There is no scope on the headers, so the top left cell could either be a row or column header and requires scope to be correct. This is indicated clearly with the read dotted line. Note that this issue was already opened and closed during previous reviews.

**Comment by drewnielson** [comment]
Agreed that table should still fail due to no scope for the top-left table header. @AnnMarieDavis, we just need to be sure that we review the examples in the training content to make sure we address this. Opened issue #320 for you or me to address in the training content. Closing this issue and moving to deployed.
