### ISSUE TITLE
Pretty sure this answer is wrong (but it was the most right of the answers) 503.4

### ISSUE THREAD

**Issue by sheribyrne** [Section508Coordinators/DHSA-TT-200-A#339]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ X] Other, specify...[replace this text with your issue type description]

## Description
[Description of the issue]

## Location
Synchronized media

## Actual Behavior / Observation
Question was about caption control, the relevant content is about captions only, but the correct answer says caption and described audio?

## Expected Behavior / Recommendation
[Describe what you expected to happen and/or your recommendation to fix or correct the issue]

## Steps to Reproduce the Issue (if applicable)
[Describes the steps you took just before you observed the issue and/or the steps necessary to reproduce again]
[caption control question set.pdf](https://github.com/Section508Coordinators/DHSA-TT-200-A/files/3576916/caption.control.question.set.pdf)

**Comment by drewnielson** [comment]
Sorry Sheri, but I haven't been able to identify the issue. Your screenshot displays a portion of the screen for Question 3, which is related to the purpose of the test for 17.B, (the multimedia provides an equivalent soundtrack for the video content). I also reviewed all of the question variants and answers that might be presented in the first 3 questions of the quiz, and I wasn't able to find a discrepancy between the question and the available answer options. Happy to investigate further, if you can provide any clarification (which I know might be difficult since you already moved on from the quiz).

I'm going to close this issue for now, but I'll re-open if you have any further description.
