### ISSUE TITLE
ANDI does not display iFrames option on Chrome

### ISSUE THREAD

**Issue by IzabellaC** [Section508Coordinators/DHSA-TT-200-A#348]
[If you haven't already, please review the [Guidelines for Contributing](contributing.md) in the main folder of this repository before submitting any issues. You can delete this paragraph and other text that is not necessary before submitting your issue.]

## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [x] Other, specify...[replace this text with your issue type description]

## Description
ANDI does not display iFrames option

## Location
Pertains to the  Topic 12: Page Titles, Frames, and iFrames

## Actual Behavior / Observation
Trying to test iFrames using ANDI. 

![image](https://user-images.githubusercontent.com/25442934/65068683-11787580-d957-11e9-89c8-1f8bb869dee1.png)

## Expected Behavior / Recommendation
I should be able to select iFrames from ANDI menu

## Steps to Reproduce the Issue (if applicable)
Select: ANDI: iframes.

**Comment by drewnielson** [comment]
@IzabellaC, very sorry for not seeing this when you originally posted. ANDI will only display the iframes module in the "Select Module" list if an iframe is present on the page. The behavior is the same in all browsers. If it is not displayed in the "Select Module" list, then ANDI has not detected an iframe. Please verify that you are testing the same page that contains an iframe and, if possible, please provide the URL for the page so we can re-produce the issue.

**Comment by IzabellaC** [comment]
Hi Andrew, Thanks for your reply. It was not clear to me at the time that
is ANDI's behavior. All good now and works as supposed to.
My other concern though is that some sites I am testing have security rules
and ANDI will not run. What is the remedy for this?

**Comment by drewnielson** [comment]
@IzabellaC, there are a few options to get around those security issues that block ANDI from loading (listed in order of ease of implementation):
* Test the page using IE 11 or earlier (because the browser itself is less secure, it doesn't have the same safeguards that the modern browsers do, and it allows ANDI to run anyway).
* Ask the site administrator to modify their site's Content Security Policy (CSP) and add the ANDI domain to their CSP's "white list" (https://www.ssa.gov/ or just the subdirectory https://www.ssa.gov/accessibility/andi/).
* Host the ANDI code from the same domain that your test site is located on. SSA provides some instructions about how to do that here: https://www.ssa.gov/accessibility/andi/help/install.html#lby-github (click the "View the Customization Instructions" button at the bottom of the page). 

Hope that helps.

**Comment by IzabellaC** [comment]
Andrew, thank you so much. This is extremely helpful.
