### ISSUE TITLE
12.C - Do Titles need to be unique? (Frame vs. page)

### ISSUE THREAD

**Issue by laurastewart-work** [Section508Coordinators/DHSA-TT-200-A#352]
## Issue Type (put a capital X between the brackets to indicate issue type)
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ ] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ X ] Other, specify...[replace this text with your issue type description]

## Description
Do Titles need to be unique?  If a frame title is the same as a page title, is it a failure? In version 4, I believe the training specified that all Titles, whether on a frame or a page, need to be unique, this was not mentioned in the v5 training.  Do unique titles apply to v5?

**Comment by drewnielson** [comment]
Hi @laurastewart-work - sorry for not being able to get to this earlier. 

No, test ID 12.C evaluates the title attribute of a `<frame>` element (i.e., `<frame title="...">`), whereas 12.A deals specifically with page titles (i.e., the inner text of a `<title>` element). It is not a problem if the value of a `title` attribute for a `<frame>` element (e.g., `<frame title="My Content">`) uses the same text as contained in the inner text of a page's `<title>` element (e.g., `<title>My Content</title>`).  Try to keep those two concepts separate (page `<title>` vs. `<frame title="...">`) as you test. 

Unique titles still apply in the same way in v5 as they did in v4: page `<title>` elements must be unique in order to differentiate between pages within a website. Whether or not a `<fame>`'s title attribute uses the same text would not affect a user's ability to differentiate between web pages.
