### ISSUE TITLE
Topic 4 Lesson 1 - Example 4 (JRR Tolkien book example)

### ISSUE THREAD

**Issue by aculbret** [Section508Coordinators/DHSA-TT-200-A#374]
#000001
- [ ] System Bug (the course doesn't function properly)
- [ ] Typo/grammar
- [ X] Incorrect content
- [ ] 508 issue (something is not accessible according to our own test process)
- [ ] Other, specify...[replace this text with your issue type description]

## Description
Passing examples - Example 4: the JRR Tolkien book, the instructions clearly show that there is a "heart" button for indicating that the book/item is a "favorite". However, your explanation that the item PASSES says (under 2. Use the keyboard to operate identified functionality....,), "You are unable to navigate to the heart button using the keyboard." If that is true, then the page FAILS.

## Location
Topic 4 Lesson 1 - Passing examples, Example 4 (under the ANDI output showing the title=Read an excerpt

## Actual Behavior / Observation
Invalid/incorrect content

## Expected Behavior / Recommendation
should say "You are ABLE to navigate to the heart button...."

## Steps to Reproduce the Issue (if applicable)
Fix/update the content to make sure it is accurate and does not mislead students.

**Comment by AnnMarieDavis** [comment]
This is not a failure for 4.A and no changes to the text are needed.  As is stated in the course:
_The heart button is not keyboard accessible, but the link “Add to favorites” provides the same functionality and is keyboard accessible._
The point of this example is to show that: Because there is an alternate way to access the functionality, it will pass 4.A despite not having access to the heart button.
