### ISSUE TITLE
Page 1 Region 3 AD button:  R3 (True for 17.B, DNA for 17.F, false for 17.D [r3e03])

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#38]
R3 (True for 17.B, DNA for 17.F, false for 17.D [r3e03])
AD is always on, but there is NO AD BUTTON, the 2 compliant AD files play at the correct times in the video. See “page 1 video instructions” for complaint audio descriptions .

Cliff: Compliant AD played, but at start of video. #1241 http://52.23.182.152/dhsv5/dhscourse/Lesson1/exams/web-incremental/testPages/index.php?studentEmail=cliff.soon@hq.dhs.gov&SCOInstanceID=97&examId=17

**Comment by mikebarklage** [comment]
Same as https://github.com/Section508Coordinators/DHSA-TT-200-A/issues/37

**Comment by Tonylayton1** [comment]
duplicate issue

**Comment by AnnMarieDavis** [comment]
This is not an exact duplicate with issue #37 which is now closed because the AD is placed in the correct location.
This issue is related to the answers.  
1. Verified 17.B is correctly indicating TRUE/Compliant
2.  Verified 17.F is correctly identifying DNA.
3. Still need fix on ANSWER ELEMENTS for 17.D. The video is missing a CC button and a AD button. The test condition is: "The media player provides user controls for closed captions AND audio description. 
 I would choose CC button AND AD button for the NC Elements.  The exam was looking for me to chose Video as the NC Element.  Answer ELEMENTS needs updating.

**Comment by Tonylayton1** [comment]
update correct reasons for 17.D. instead of r3_03, the correct answers should be r3_09 and r3_10. documentation is updated.

**Comment by mikebarklage** [comment]
Answers have been updated.

**Comment by AnnMarieDavis** [comment]
Verified
