### ISSUE TITLE
"OFTE 251 Trusted Tester Certification Exam"

### ISSUE THREAD

**Issue by srilakshmirepalli** [Section508Coordinators/DHSA-TT-200-A#389]
Hi 

I need help ,I missed two questions on the “Auto-Playing and Auto-Updating Content-Incremental Practical Exam and received a 50%.   I changed my answers to the incorrect question and resubmitted my exam. The system is  not saving my updated answer to missing exam question.  The system continues to report I received 50% even after I selected all possible answers. 

Thank you in advance for your help!!!

**Comment by AnnMarieDavis** [comment]
This is not an exam issue (course bug) These types of questions should be directed to the Q&A Boards.

The issue is not the exam.  The course randomizes the version of the exam and the answer may be different for each try.  It may have been a FAIL on the first version presented to you. You would get it wrong if you marked PASS.  The next attempt might present you with a different version where PASS is the correct answer. You must RETEST each page, not put something different.
