### ISSUE TITLE
Incremental Topic 4: new 4.F issue

### ISSUE THREAD

**Issue by Tonylayton1** [Section508Coordinators/DHSA-TT-200-A#420]
When 4.F fails, add a new failure to the page. Move the "Prefered method of contact" dropdown box to be the last item on the page that recieves tabbing order focus. Add r2e12 to the list of failures for 4.F.
The complete list of failures for 4.F should then be: r2e04, r2e09, r2e12

4.F should now only fail alongside 4.C - 4.A and 4.F/4.G should be independent

Note to Mike: it may help to make the other changes before you make this one.

**Comment by mikebarklage** [comment]
This is updated on Dev.

I am reminded that we went away from specifying tabIndex values because in certain browsers the focus could vanish or go to unintended elements. I tried to keep an eye out for that - Firefox includes the entire page in its tab order, which I don't know if I can fix, but at least it provides a visual outline.

I don't recall offhand OAST decide to handle that, or if other issues arose that I'm forgetting.

**Comment by Tonylayton1** [comment]
the element before the dropdown is a radio button field. If the 1st radio is toggled (or user is tabbing through without changing it), the dropdown will be skipped in tabbing order as intended. However if any of the other radios are toggled, the dropdown will be next in tabbing order but focus will be at the bottom of the page if I tab backwards. It's as if the other 3 radio buttons are grouped with the dropdown at the bottom of the page.

**Comment by mikebarklage** [comment]
I think I figured out a way around this, by giving every radio button the same tabIndex value. Side effect: tabbing through the radio buttons without selecting one, then tabbing back, puts focus on the last radio button (Over 200) instead of the first one (25 or less). But maybe that's OK.

Is this an issue on any of the other exams?

**Comment by Tonylayton1** [comment]
Verified on dev. The issue was only on this page and also the last radio button getting focused when approaching from the opposite direction is normal.

**Comment by AnnMarieDavis** [comment]
https://exams-dev.section508testing.net/dhsv5/dhscourse/Lesson1/exams/web-practice/testPages/page2_main.php?KeyID=71732
In Firefox, when I select the I want to upgrade radio button, the Device ID text box is skipped in the tab order. Otherwise the the Device ID text box appears to get keyboard focus.  I think the fix broke something...

**Comment by mikebarklage** [comment]
I don't see this exact behavior in Firefox myself, but if 5.D is NC, then the Device ID box and Get Code button are flipped in the tab order. Could it be related to that?

**Comment by AnnMarieDavis** [comment]
The answer sheets seem out of sync.  On Request an Audit for my last Incremental topic 4 exam still an issue. KeyID=71750. Focus goes from Zip to 25 or less employees to Get Super Certified check box. Skips Preferred Method of Contact. 4.A is looking for Pass.

**Comment by mikebarklage** [comment]
When 4.F fails, the tab order for Preferred Method of Contact is shifted to be the last item on the page. Do we need to also add it to the failures for 4.A?

**Comment by AnnMarieDavis** [comment]
yes, when focus skips Preferred Method of Contact (in these 4.F failures), there should be failure for it in 4.A as well.

**Comment by Tonylayton1** [comment]
I'm confused. the element is accessible, it is just out of order. Preferred Method of Contact" is focused last on the page. How is this a 4.A failure if it is accessible with a keyboard?

**Comment by AnnMarieDavis** [comment]
OAST verified. It is not a 4.A failure since order goes to Preferred Method of Contact after the last menu item at the bottom of the page.
