### ISSUE TITLE
Page 2, Region 3 R3 (True for 14.A, false for 14.B [r3e04 ])

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#46]
Present the data table as shown in the PSD and identify with the HTML <table> attribute, where each image is inside the correct “td” cell. The top row is comprised of “th” cells with no scope and the leftmost column is comprised of “th” cells with “no scope”

Cliff: Should be C; th is sufficient for simple tables. To fail, remove th?
![image](https://user-images.githubusercontent.com/34742733/59108644-642ea400-8909-11e9-9be2-30e88fe05045.png)

**Comment by drewnielson** [comment]
@cliffbert, we discussed this a little more during the meeting with Carney earlier today. Tony and Mike pointed out that the "Measured Effects" header really should have a scope="col" in order to pass. Otherwise, it is ambiguous whether it should serve as a column or a row header. ANDI also throws a warning to this effect. I agree that this example should still probably fail due to lack of the scope attribute.

**Comment by Tonylayton1** [comment]
as per above discussion, no change

**Comment by AnnMarieDavis** [comment]
This issue identified here with scope is verified.

HOWEVER: There is an error on the incremental practice exam answer sheet **when the table is NC for 14.A due to the table being coded role="presentation"**. In these cases, 14.B should be DNA on the answer sheet because ANDI does not identify the table cells.

**Comment by Tonylayton1** [comment]
Is this true? the test process for 14.B says "This Test Condition DOES NOT APPLY (DNA) if there are no data tables on the page." Isn't it still a data table regardless of whether it is correctly marked up?

**Comment by drewnielson** [comment]
Appologies @AnnMarieDavis, but I disagree. If we identify it as a data table, then we still evaluate both 14.A and 14.B, and it should fail for both. Since the original issue is verified as fixed, I'll close this issue. We can discuss whether or not there is still a separate issue with 14.B and open another issue, if necessary.
