### ISSUE TITLE
Page 2, region 4  R3 (True for 13.B, and 15.B, and 15.C, False for 10.D [r4e04, r4e06 ])

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#50]
R3 (True for 13.B, and 15.B, _and 15.C,_ False for 10.D [r4e04, r4e06 ])
The two lists appear as they do in the mockup. 
When viewed inline without CSS, the headers and lists are ordered correctly on the page as follows: “Standard Certified” header, Standard Certified list items, “Super-Certified” header, Super Certified list items. 
Each group of list items are not nested in a list tag.

Comments: 15C has a strike through it

Cliff:The details page mentions “list stem” – not sure what that means, and not sure student will know. Maybe “list header”? Exam #1231
![image](https://user-images.githubusercontent.com/34742733/59109644-68f45780-890b-11e9-9bee-ac8ded0769b8.png)

**Comment by KSmithO** [comment]
Agreed-confusing. Seems like easy change?

**Comment by mikebarklage** [comment]
Fixed on Dev, waiting for approval.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
Verified 13  and 15 choice changed to "list header". 

In the Q&A sessions with the pilot group, they recommended using " list bold text" instead of "list header". If the OAST team determines this is the preferred label for the checkbox on the answer sheet, a new issue will need to be opened in GitHub.
