### ISSUE TITLE
page 3, region 3: If asked, could you supply employee testimony? (fieldset legend), R2 (False for 4.C [r3e09], 4.F [r3e09] and 4.H  [r3e09])

### ISSUE THREAD

**Issue by KSmithO** [Section508Coordinators/DHSA-TT-200-A#60]
R2 (False for 4.C [r3e09], 4.F [r3e09] and 4.H  [r3e09])
As above, but selecting tab when in this fieldset moves focus to the top of the page.

Two Comments:

1. 4.F is highlighted-unsure what that means.
2. Cliff comment on 4.H-This is a tricky one. Since the test process says to try to close the revealed content, maybe should use a checkbox to allow uncheck and hide, since cannot uncheck the radio button (or add a No radio button to re-hide the content)

**Comment by mikebarklage** [comment]
On Dev, changed radio button to checkbox to toggle display on or off, waiting for approval.

**Comment by Tonylayton1** [comment]
verified on dev

**Comment by AnnMarieDavis** [comment]
1. Verified - Check box was added to ensure 4.H  is added to text box. Test result is reporting correctly.
2. STILL an ISSUE - For 4.G the exam is expecting a result of C for Focus is moved to revealed content, but focus jumps back to the top of the page forcing the user to navigate backwards to get focus on the revealed content. 
3. STILL an ISSUE - 4.F, 2.4.3 Focus Order meaning how to mark these clearer ON ANSWER SHEET itself
4. STILL an ISSUE - 4.C, 2.1.2-no-keyboard-trap - this should be marked C because you can navigate backwards to State Text and associated text entry field. The current expected response is

**Comment by Tonylayton1** [comment]
1. "For 4.G the exam is expecting a result of C for Focus is moved to revealed content, but focus jumps back to the top of the page forcing the user to navigate backwards to get focus on the revealed content."

- cannot replicate. When the answer sheet says "c" for 4.G and 4.H, the focus goes to the next object when revealed content is revealed or hidden. when it says "nc" for 4.G and 4.H, it goes to the top of the page when content is revealed or hidden. note: because 2 IDs rely on the same object on the web-page, manipulating them in the answer sheet manually would result in the issue described.

2. "4.F, 2.4.3 Focus Order meaning how to mark these clearer ON ANSWER SHEET itself"

- Is this in reference to updating the answer sheet manually? Currently the only variable than can be manipulated directly on the answer sheet is whether or not the ID is compliant.

3.  "4.C, 2.1.2-no-keyboard-trap - this should be marked C because you can navigate backwards to State Text and associated text entry field. The current expected response is"

- Currently the keyboard trap moves the focus up to the "Company name" field when attempting to tab beyond the "state" text entry field. We will update so user can also not reverse tab beyond the "Company name" field. [note to mike: this will add "r2_03" to both the failure reasons for 4.C and 4.F]

**Comment by mikebarklage** [comment]
I've changed the keyboard trap with a new method and added r2_3 to the DB.

**Comment by Tonylayton1** [comment]
Mostly verified, but I made a mistake on the documentation. The keyboard trap on the webpage leads up to the "contact name" field, not the "company name field". leave the page the same, but update the new correct answer for 4.C and 4.F from r2_03 to r2_04

**Comment by mikebarklage** [comment]
OK, answers are updated.

**Comment by Tonylayton1** [comment]
Verified. Moving to "Review" but still one question about one of the comments above:

"4.F, 2.4.3 Focus Order meaning how to mark these clearer ON ANSWER SHEET itself"
Is this in reference to updating the answer sheet manually? Currently the only variable than can be manipulated directly on the answer sheet is whether or not the ID is compliant.

**Comment by AnnMarieDavis** [comment]
Verified update to page for keyboard trap 4.C 

For URL to Test Key ID=1444 focus order 
4.F - I simply don't see what issue with Contact Name made this an NC. (Other 2 answers for this page are correct) Focus order went from left to right from Company Name to Contact Name to HR Email to Company Phone... See nothing that interferes with the meaning or operability of the page for that particular element. ANDI tab order does insert a tab # there, but I experienced no issue with the tab landing there.

**Comment by Tonylayton1** [comment]
Yes you're right. the reverse tab stoppage on this element doesn't affect the order so we will remove r2_04 from 4.F when this failure occurs.

**Comment by mikebarklage** [comment]
OK, done.

**Comment by Tonylayton1** [comment]
verified

**Comment by drewnielson** [comment]
verified in dev
